[web_server]
host = "0.0.0.0"
port = 8080

[database]
path = "surl.db" #数据库地址，不存在会自动创建

[rate_limits]
limit = 100 #写什么都行，暂时没作用


[jwt]
# JWT 签名密钥
secret_key = "123456"
# Token 有效时间（单位：秒）
token_duration = 86400


[site]
# 站点 URL
base_url = "http://localhost:8080"
# 站点名称
site_name = "ShortURL Service"
# 是否允许游客创建短链
allow_guest_to_create_url = true
# 是否允许用户注册
allow_registration = true

[smtp]
# SMTP 服务器地址
server = "smtp.example.com"
# SMTP 端口（465 = SSL，587 = STARTTLS）
port = 465
# SMTP 用户名
username = "your-email@example.com"
# SMTP 密码
password = "YOUR_SMTP_PASSWORD"